In [1]:
import numpy as np

### creating array from list

In [4]:
import numpy as np

arr_1d=np.array([1,2,3,4,5])
print("1D array:",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array:\n",arr_2d)


arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("3D array:\n",arr_3d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### List vs numpy array


In [ ]:
import numpy as np

py_list=[1,2,3]
print("python list multiplication",py_list * 2)

np_array=np.array([1,2,3])
print("python array multiplicatiobn ",np_array * 2)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplicatiobn  [2 4 6]


In [10]:
import time 
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n list operation time:",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation timeL ",time.time()-start)



 list operation time: 0.06547188758850098

 Numpy operation timeL  0.00585174560546875


### creating array from scratch


In [ ]:
zeros=np.zeros((3,4))
print("Zeroes array:\n",zeros)

ones = np.ones((2,3))
print("one array:\n",ones)

# requare a asecial element
full=np.full((2,2),7) 
print("full array\n",full)

random=np.random.random((2,3))
print("random array:\n",random)


sequence=np.arange(0,10,2)
print("sequence array:\n",sequence)


Zeroes array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array
 [[7 7]
 [7 7]]
random array:
 [[0.50875469 0.78474055 0.90875364]
 [0.70999016 0.38175314 0.56659222]]
sequence array:
 [0 2 4 6 8]


### vector , matrix and Tensor ###


In [11]:
vector = np.array([1,2,3])
print("vector:",vector)

matrix=np.array([[1,2,3],
                 [4,5,6]])
print("matrix:",matrix)

tensor = np.array([[[[1,2],[3,4],
                   [5,6],[7,8] ]]])
print("tensor:",tensor)



vector: [1 2 3]
matrix: [[1 2 3]
 [4 5 6]]
tensor: [[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]


### Array properties 

In [16]:
arr=np.array([[1,2,3],
              [4,5,"6.8"]])
print("shap",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)

shap (2, 3)
Dimension 2
size 6
Dtype <U21


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("original array",arr)

reshaped=arr.reshape((3,4))
print("\nReshaped array\n",reshaped)
# print("size",reshaped.size)
# print("Dimension",reshaped.ndim)
# print("shap",reshaped.shape)
flatend=reshaped.flatten()
print("\n Flattened array",flatend)

# ravel (return view,instend of copy)
raveled=reshaped.ravel()
print("\n raveled array",raveled)


original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shap (3, 4)

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Transpose of matrix



In [34]:
transpose=reshaped.T
print("\n Transpose array\n",transpose)
print("size",transpose.size)
print("Dimension",transpose.ndim)
print("shap",transpose.shape)


 Transpose array
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
size 12
Dimension 2
shap (4, 3)
