### Numpy Array operations

In [10]:
import numpy as np

In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing",arr[2:7])
print("with step",arr[1:8:2])
print("negative indexing ",arr[-3])

Basic slicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing  8


In [12]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element",arr_2d[1,2])
print("Entire  row",arr_2d[1])
print("Entire row",arr_2d[:,1])

Specific element 6
Entire  row [4 5 6]
Entire row [2 5 8]


SORTING

In [13]:
unsorted=np.array([3,1,4,5,9,2,6])
print("sorted array",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("sorted 2D array by column\n",np.sort(arr_2d_unsorted, axis=0))
print("sorted 2D array by rows\n",np.sort(arr_2d_unsorted,axis=1))
 

sorted array [1 2 3 4 5 6 9]
sorted 2D array by column
 [[1 1]
 [2 2]
 [3 3]]
sorted 2D array by rows
 [[1 3]
 [1 2]
 [2 3]]


### Filter


In [14]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers %2==0]
print("Even numbers",even_numbers)

Even numbers [ 2  4  6  8 10]


Filter with mask

In [15]:
mask=numbers > 5
print("Number greater than 5",numbers[mask])

Number greater than 5 [ 6  7  8  9 10]


Fancy indexing vs np.where()

In [16]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers > 5)
print(where_result)
print("NP where",numbers[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [17]:
import numpy as np
# np.where function is a type of function which is use to fid index based condition
codition_array=np.where(numbers > 5, numbers*4, numbers)
print(codition_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [22]:
condition_array = np.where(numbers > 5 , "true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


Adding and removing data

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print(combined) 

[1 2 3 4 5 6]


In [25]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print(combined) 

[1 2 3 4 5 6]


array compatibilty

In [30]:
a =np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,0,])
print("Compatibility shapes",a.shape == b.shape ==c.shape)

Compatibility shapes True


In [ ]:
original = np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
# /np.vstack = vertical stack
# /it  addds new rows (oone below the other)
# it stack arrays row-wise(vertically)
with_new_row = np.vstack((original,new_row))
print("original matrix\n",original)
print("with_new_row\n",with_new_row)

original matrix
 [[1 2]
 [3 4]]
with_new_row
 [[1 2]
 [3 4]
 [5 6]]


In [40]:
original = np.array([[1,2],[3,4]])
new_col=np.array([[7],[8]])
# /np.vstack = horizontal stack
# /it  addds new column (side by side)

with_new_col = np.hstack((original,new_col))
print("original matrix\n",original)
print("with_new_col\n",with_new_col)

original matrix
 [[1 2]
 [3 4]]
with_new_col
 [[1 2 7]
 [3 4 8]]


In [41]:
# delating element from array
arr=np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion:",deleted)

Array after deletion: [1 2 4 5]
